name: Continuous Integration
on: 
    push:
        branches:
            - main
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
        - name: Simulando Continuous Delivery
          uses: actions/upload-artifact@v4
          with:
              name: projetocompactado
              path: ../projetosoa/
